### ISSUE TITLE
User can make malicious transaction verifier

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/chamber-packages#181]
If a user adds the malicious transaction verifier that return always `true` after plasma chain launched, 
the operator can challenge any correct exits. So the operator can steal users asset.

To avoid this problem, we should introduce state based verifier like TxVM.
Once users lock their asset, any new type of transactions can't unlock unfairly.

**Comment by shogochiai** [comment]
> state based verifier like TxVM

You mean, the simplest form of this verifier is, "put signature checker with value"?

![screen shot 2019-03-07 at 9 45 36](https://user-images.githubusercontent.com/4891004/53924044-cf27cf00-40bd-11e9-9309-f59b4915ef2f.png)

**Comment by syuhei176** [comment]
Yes but we can't use byte code. So I think We need StateVerifier like State Unlocker contract.
